"""ML, audit and feedback tables

Revision ID: 7be5f526d699
Revises: 001_initial
Create Date: 2026-08-27 01:01:26.662970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be5f526d699'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coverage_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_type'), 'data_sources', ['type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('delay_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('delay_label', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delay_outcomes_delay_label'), 'delay_outcomes', ['delay_label'], unique=False)
    op.create_index(op.f('ix_delay_outcomes_id'), 'delay_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_delay_outcomes_project_id'), 'delay_outcomes', ['project_id'], unique=False)
    op.create_table('project_feature_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feature_json', sa.JSON(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_feature_snapshots_id'), 'project_feature_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_project_feature_snapshots_is_synthetic'), 'project_feature_snapshots', ['is_synthetic'], unique=False)
    op.create_index(op.f('ix_project_feature_snapshots_project_id'), 'project_feature_snapshots', ['project_id'], unique=False)
    op.create_table('prediction_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('risk_class', sa.String(length=20), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('is_mock_prediction', sa.Boolean(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['project_feature_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_results_id'), 'prediction_results', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_results_predicted_at'), 'prediction_results', ['predicted_at'], unique=False)
    op.create_index(op.f('ix_prediction_results_project_id'), 'prediction_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_prediction_results_risk_class'), 'prediction_results', ['risk_class'], unique=False)
    op.create_table('project_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('flagged_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_flags_id'), 'project_flags', ['id'], unique=False)
    op.create_index(op.f('ix_project_flags_project_id'), 'project_flags', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_flags_status'), 'project_flags', ['status'], unique=False)
    op.create_table('shap_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=True),
    sa.Column('contribution_value', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shap_explanations_id'), 'shap_explanations', ['id'], unique=False)
    op.create_index(op.f('ix_shap_explanations_prediction_id'), 'shap_explanations', ['prediction_id'], unique=False)
    op.create_table('what_if_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('base_prediction_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_features_json', sa.JSON(), nullable=False),
    sa.Column('resulting_risk_class', sa.String(length=20), nullable=False),
    sa.Column('resulting_probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_prediction_id'], ['prediction_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_what_if_scenarios_id'), 'what_if_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_what_if_scenarios_project_id'), 'what_if_scenarios', ['project_id'], unique=False)
    op.create_index(op.f('ix_acquisition_stage_history_id'), 'acquisition_stage_history', ['id'], unique=False)
    op.create_index(op.f('ix_compensation_records_id'), 'compensation_records', ['id'], unique=False)
    op.create_index(op.f('ix_litigations_id'), 'litigations', ['id'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index(op.f('ix_litigations_id'), table_name='litigations')
    op.drop_index(op.f('ix_compensation_records_id'), table_name='compensation_records')
    op.drop_index(op.f('ix_acquisition_stage_history_id'), table_name='acquisition_stage_history')
    op.drop_index(op.f('ix_what_if_scenarios_project_id'), table_name='what_if_scenarios')
    op.drop_index(op.f('ix_what_if_scenarios_id'), table_name='what_if_scenarios')
    op.drop_table('what_if_scenarios')
    op.drop_index(op.f('ix_shap_explanations_prediction_id'), table_name='shap_explanations')
    op.drop_index(op.f('ix_shap_explanations_id'), table_name='shap_explanations')
    op.drop_table('shap_explanations')
    op.drop_index(op.f('ix_project_flags_status'), table_name='project_flags')
    op.drop_index(op.f('ix_project_flags_project_id'), table_name='project_flags')
    op.drop_index(op.f('ix_project_flags_id'), table_name='project_flags')
    op.drop_table('project_flags')
    op.drop_index(op.f('ix_prediction_results_risk_class'), table_name='prediction_results')
    op.drop_index(op.f('ix_prediction_results_project_id'), table_name='prediction_results')
    op.drop_index(op.f('ix_prediction_results_predicted_at'), table_name='prediction_results')
    op.drop_index(op.f('ix_prediction_results_id'), table_name='prediction_results')
    op.drop_table('prediction_results')
    op.drop_index(op.f('ix_project_feature_snapshots_project_id'), table_name='project_feature_snapshots')
    op.drop_index(op.f('ix_project_feature_snapshots_is_synthetic'), table_name='project_feature_snapshots')
    op.drop_index(op.f('ix_project_feature_snapshots_id'), table_name='project_feature_snapshots')
    op.drop_table('project_feature_snapshots')
    op.drop_index(op.f('ix_delay_outcomes_project_id'), table_name='delay_outcomes')
    op.drop_index(op.f('ix_delay_outcomes_id'), table_name='delay_outcomes')
    op.drop_index(op.f('ix_delay_outcomes_delay_label'), table_name='delay_outcomes')
    op.drop_table('delay_outcomes')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_data_sources_type'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
