"""project coordinates for map view

Revision ID: 994a98026d7d
Revises: 7be5f526d699
Create Date: 2026-08-27 09:50:59.396997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994a98026d7d'
down_revision: Union[str, None] = '7be5f526d699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'longitude')
    op.drop_column('projects', 'latitude')
    # ### end Alembic commands ###
