"""rehabilitation progress

Revision ID: ddaba4e9f2ac
Revises: 994a98026d7d
Create Date: 2026-08-27 11:05:10.632111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddaba4e9f2ac'
down_revision: Union[str, None] = '994a98026d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('rehabilitation_progress_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'rehabilitation_progress_pct')
    # ### end Alembic commands ###
